version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_HOST}
    ports:
      - 5432:5432
    networks:
      - app
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    image: oven/bun:1-slim
    command: bun dev
    working_dir: /app
    tty: true
    ports:
      - 3000:3000
    networks:
      - app
    depends_on:
      - db
    volumes:
      - ./:/app
      - db-data:/var/lib/postgresql/data

networks:
  app:
    driver: bridge

volumes:
  db-data:
