version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_HOST}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  studio:
    image: node:20
    command: npx prisma studio
    working_dir: /app
    depends_on:
      - db
    ports:
      - 5555:5555
    volumes:
      - ./:/app
  app:
    image: oven/bun:1-slim
    command: bun dev
    working_dir: /app
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./:/app
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
